version: '2'
services:
    doris-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/doris/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=doris
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
